const categories=[['🍽️','Restaurants'],['🎟️','Events'],['🏪','Businesses'],['⚽','Activities'],['👥','Groups'],['🛍️','Marketplace']];
const restaurants=[['Levant Grill','Syrian & Lebanese plates, shawarma, kebab and family platters.','Halal','Catering','🍢'],['Cedar Sweets Café','Kunafa, baklava, Arabic coffee, desserts and party trays.','Desserts','Coffee','🍰'],['Nile Kitchen','Egyptian comfort food, grilled meats and weekend specials.','Family','Pickup','🍲']];
const businesses=[['Arabic-Speaking CPA','Tax preparation, bookkeeping and small business accounting.','Finance','Verified','📊'],['Immigration Law Office','Consultation for visas, family cases and business immigration.','Legal','Consultation','⚖️'],['Arab Realtor Network','Residential and commercial real estate support in multiple states.','Real Estate','Homes','🏡']];
const events=[['Arab Culture Night','Music, food, dabke, vendors and networking for families.','$25','Tickets','🎶'],['Small Business Mixer','Meet Arab-American founders, vendors, real estate and service providers.','Free','RSVP','🤝'],['Family Soccer Meetup','Community soccer games and kids activities every Saturday.','$10','Activity','⚽']];
const groups=[['Arabs in Virginia','A local group for families, students, professionals and business owners in VA.','2.4k members','Join','🌙'],['Arab Business Owners USA','Promote your business, network, hire and collaborate with owners nationwide.','1.7k members','Join','💼'],['Arab Students Network','Support for new students, housing, jobs, events and campus life.','920 members','Join','🎓']];
const markets=[['Restaurant Manager Needed','Full-time position at a Mediterranean restaurant in Northern Virginia.','Job','Apply','💼'],['Room for Rent','Private room near metro, family-friendly area, Arabic-speaking household.','Housing','Contact','🏠'],['Event Photographer','Available for weddings, parties, community events and business openings.','Service','Book','📸']];
const posts=[['Maya A.','Looking for recommendations for the best kunafa and Arabic coffee in Northern Virginia. Any favorite places?','#Food'],['Omar K.','We are organizing a family soccer meetup this Saturday. Kids and adults welcome.','#Activities'],['Lina S.','New Arabic language class for children starting next month. Message me for details.','#Education']];
function card(x){return `<article class="card searchable" data-keywords="${x.join(' ').toLowerCase()}"><div class="listing-img">${x[4]}</div><h3>${x[0]}</h3><p>${x[1]}</p><span class="tag">${x[2]}</span><span class="tag">${x[3]}</span><br><br><button class="secondary" onclick="openModal('joinModal')">View Details</button></article>`}
function renderCards(list,id){document.getElementById(id).innerHTML=list.map(card).join('')}
document.getElementById('categoryGrid').innerHTML=categories.map(c=>`<div class="category searchable" data-keywords="${c.join(' ').toLowerCase()}"><span class="ico">${c[0]}</span>${c[1]}</div>`).join('');
renderCards(restaurants,'restaurantList');renderCards(businesses,'businessList');renderCards(events,'eventList');renderCards(groups,'groupList');renderCards(markets,'marketList');
document.getElementById('postList').innerHTML=posts.map(p=>`<article class="post searchable" data-keywords="${p.join(' ').toLowerCase()}"><div class="post-head"><div class="avatar">${p[0][0]}</div><div><b>${p[0]}</b><br><span class="tag">${p[2]}</span></div></div><p>${p[1]}</p><div class="post-actions"><span>♡ Like</span><span>💬 Comment</span><span>↗ Share</span></div></article>`).join('');
function openModal(id){document.getElementById(id).classList.add('show')}function closeModal(id){document.getElementById(id).classList.remove('show')}
function filterCards(){const q=document.getElementById('searchInput').value.toLowerCase();document.querySelectorAll('.searchable').forEach(c=>{const text=(c.innerText+' '+(c.dataset.keywords||'')).toLowerCase();c.style.display=text.includes(q)?'block':''})}
let ar=false;document.getElementById('langBtn').onclick=()=>{ar=!ar;document.body.classList.toggle('ar',ar);document.getElementById('langBtn').innerText=ar?'English':'العربية';document.querySelector('[data-i18n="heroTitle"]').innerText=ar?'منصة تربط العرب والأمريكيين بالمطاعم والفعاليات والخدمات والمجتمع في كل الولايات المتحدة.':'Connect, discover and celebrate Arab culture across the United States.';document.querySelector('[data-i18n="heroLead"]').innerText=ar?'دليل USArab يساعد الجالية العربية والأمريكيين على اكتشاف المطاعم، الفعاليات، الشركات، الأنشطة، المجموعات والدعم المجتمعي في مكان واحد.':'USArab Guide helps Arabs, Arab Americans and Americans find restaurants, events, businesses, activities, groups and community support in one trusted platform.'}
